version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: symfony_dev:latest
    container_name: symfony_monitoring_php
    volumes:
      - ./symfony/:/var/www/symfony
    working_dir: /var/www/symfony

  nginx:
    image: nginx:stable
    container_name: symfony_monitoring_nginx
    ports:
      - "9443:443"
      - "9100:9100" # prometheus
    volumes:
      - ./symfony/:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - php

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx_exporter
    depends_on:
      - nginx
    environment:
      - HOST=0.0.0.0
      - PORT=9113
    command:
      # listen on 9113
      - "--web.listen-address=:9113"
      # metrics path (default is /metrics)
      - "--web.telemetry-path=/metrics"
      # scrape the HTTP stub_status on port 80
      - "--nginx.scrape-uri=http://nginx:80/nginx_status"
    ports:
      - "9113:9113"

  prometheus:
    image: prom/prometheus:latest
    container_name: symfony_monitoring_prometheus
    ports:
      - "9099:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:latest
    container_name: symfony_monitoring_grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: symfony_monitoring_k6
    volumes:
      - ./loadtests:/scripts:ro
    environment:
      API_BASE: "https://localhost:9443/api/monitoring/v1"
    network_mode: host
    depends_on:
      - nginx
    command: [
      "run",
      "--address","0.0.0.0:6565",
      "--insecure-skip-tls-verify",
      "/scripts/load-test.jsx"
    ]

volumes:
  grafana_data:

