{
 "title": "Symfony App Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "route",
    "label": "Route",
    "query": "label_values(symfony_app_http_request_duration_seconds_bucket, route)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(symfony_app_http_requests_total{action=\"all\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(symfony_app_http_4xx_responses_total[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Latency P90 (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(symfony_app_http_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "NGINX Connections Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nginx_connections_accepted{job=\"nginx_monitoring\"}"
    }
   ]
  }
 ]
}