global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'symfony_app'
    metrics_path: /metrics/prometheus
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - symfony_monitoring_nginx:9100
  - job_name: 'nginx_monitoring'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'nginx_exporter:9113' ]